USE Regjisterdb
GO
CREATE TABLE ROLES(
	ID INT PRIMARY KEY IDENTITY(1, 1),
	CODE VARCHAR(10) UNIQUE,
	DESCRIPTION VARCHAR(50)
);

SELECT * FROM ROLES;

CREATE TABLE USERS(
	ID INT PRIMARY KEY IDENTITY(1, 1),
	EMER_MBIEMER VARCHAR(50),
	EMAIL VARCHAR(50) UNIQUE,
	ROLE_ID INT,
	PASSWORD VARCHAR(50),
	FOREIGN KEY(ROLE_ID) REFERENCES ROLES(ID),

);

ALTER TABLE USERS ADD USERNAME VARCHAR(50) UNIQUE;

CREATE TABLE DEPARTAMENT(
	ID INT PRIMARY KEY IDENTITY(1, 1),
	EMER VARCHAR(50)
);
ALTER TABLE DEPARTAMENT ADD CODE VARCHAR(50) UNIQUE;
ALTER TABLE DEPARTAMENT ADD STATUS INT;
select * from DEPARTAMENT;

CREATE TABLE LENDET(
	ID INT PRIMARY KEY IDENTITY(1, 1),
	EMER VARCHAR(50) UNIQUE,
	DEPARTAMENT_ID INT,
	FOREIGN KEY(DEPARTAMENT_ID) REFERENCES DEPARTAMENT(ID)
);

insert into lendet (emer,DEPARTAMENT_ID) values ('Programim i avancuar', 1);

select * from lendet;

CREATE TABLE SALLA(
	ID INT PRIMARY KEY IDENTITY(1, 1),
	EMER VARCHAR(50) UNIQUE
);
select * from salla;
insert into salla (emer) values ('103');

CREATE TABLE GROUPS(
	ID INT PRIMARY KEY IDENTITY(1, 1),
	EMER VARCHAR(50)
);
select * from groups;
insert into groups(emer, viti_akademik, dega, code) values ('A', '2024-2025', 'Inxhinieri Informatike', 'A-2024-2025-FTI');
insert into groups(emer, viti_akademik, dega, code) values ('B', '2024-2025', 'Inxhinieri Informatike', 'B-2024-2025-FTI');
insert into groups(emer, viti_akademik, dega, code) values ('C', '2024-2025', 'Inxhinieri Informatike', 'C-2024-2025-FTI');
ALTER TABLE GROUPS ADD VITI_AKADEMIK VARCHAR(50);
ALTER TABLE GROUPS ADD DEGA VARCHAR(50);
ALTER TABLE GROUPS ADD CODE VARCHAR(100) UNIQUE;
ALTER TABLE GROUPS ADD UNIQUE(EMER, VITI_AKADEMIK, DEGA);


CREATE TABLE STUDENT(
	ID INT PRIMARY KEY IDENTITY(1, 1),
	USER_ID INT,
	CARD_ID VARCHAR(50),
	GROUP_ID INT,
	FOREIGN KEY (GROUP_ID) REFERENCES GROUPS(ID),
	FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);
DROP TABLE PROFESOR;
CREATE TABLE PROFESOR(
	ID INT PRIMARY KEY IDENTITY(1, 1),
	USER_ID INT,
	DEPARTAMENT_ID INT,
	FOREIGN KEY(DEPARTAMENT_ID) REFERENCES DEPARTAMENT(ID),
	FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);

select * from profesor;
insert into profesor()

CREATE TABLE ORAR_MESIMOR(
	ID INT PRIMARY KEY IDENTITY(1, 1),
	LENDA_ID INT,
	GROUP_ID INT,
	PROFESOR_ID INT,
	SALLA_ID INT,
	DITA_E_JAVES INT, --(1-5)
	NGA_ORA INT,
	DERI_NE_ORA INT,
	FOREIGN KEY (LENDA_ID) REFERENCES LENDET(ID),
	FOREIGN KEY (GROUP_ID) REFERENCES GROUPS(ID),
	FOREIGN KEY (PROFESOR_ID) REFERENCES PROFESOR(ID),
	FOREIGN KEY (SALLA_ID) REFERENCES SALLA(ID)
);

ALTER TABLE ORAR_MESIMOR ADD UNIQUE (SALLA_ID, DITA_E_JAVES, NGA_ORA, DERI_NE_ORA);
ALTER TABLE ORAR_MESIMOR ADD UNIQUE (LENDA_ID, GROUP_ID, PROFESOR_ID, SALLA_ID, DITA_E_JAVES, NGA_ORA, DERI_NE_ORA);

select * from ORAR_MESIMOR;

update ORAR_MESIMOR set PROFESOR_ID = 2;



CREATE TABLE PJESEMARRJA(
	ID INT PRIMARY KEY IDENTITY(1, 1),
	STUDENT_ID INT,
	ORAR_MESIMOR_ID INT,
	PREZENT INT DEFAULT 0, -- 0 == FALSE, 1 == TRUE
	KOHA_E_CHECKIN TIMESTAMP,
	FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(ID),
	FOREIGN KEY (ORAR_MESIMOR_ID) REFERENCES ORAR_MESIMOR(ID)
);

select * from STUDENT where CARD_ID = '2f1aa54a-8622-4f62-b44b-ccf075a22993'

INSERT INTO ROLES(CODE, DESCRIPTION) VALUES('ADMIN', 'ADMINISTRATOR');
INSERT INTO ROLES(CODE, DESCRIPTION) VALUES('SCRT', 'SEKRETARIA MESIMORE');
INSERT INTO ROLES(CODE, DESCRIPTION) VALUES('PRF', 'PROFESOR');
INSERT INTO ROLES(CODE, DESCRIPTION) VALUES('STD', 'STUDENT');

INSERT INTO USERS(EMER_MBIEMER, EMAIL,ROLE_ID,PASSWORD) VALUES('KLEA SPAHO', 'klea@info.com', (SELECT ID FROM ROLES WHERE CODE = 'ADMIN'), 'supersecret');

select * from users;
select * from student;
delete from users where username = 'anahoxha';
select * from roles;
select * from PROFESOR;
select * from DEPARTAMENT;
select * from lendet;
select * from GROUPS;
select * from SALLA;
select * from ORAR_MESIMOR;
alter table ORAR_MESIMOR add STATUS INT DEFAULT 0;
select * from PJESEMARRJA;
insert into ORAR_MESIMOR(LENDA_ID, GROUP_ID, PROFESOR_ID, SALLA_ID,DITA_E_JAVES, NGA_ORA, DERI_NE_ORA) values (2, 2, 2, 1, 1, 10, 11);
insert into PJESEMARRJA(STUDENT_ID, ORAR_MESIMOR_ID, PREZENT, KOHA_E_CHECKIN) values (6, 4, 1, CAST(GETDATE() AS DATE))
insert into DEPARTAMENT (code, emer) values ('inf', 'Inxhinieri informatike');
insert into DEPARTAMENT (code, emer) values ('mat', 'Inxhinieri matematike');

delete from users where username = 'agimdisha';

update student set group_id= 2 where id = 2;
